name: Lint

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      ref:
        required: true
        description: "GitHub ref to use"
        type: string
      version-set:
        required: true
        description: "Version matrix to use"
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Must match the `version:` field in .custom-gcl.yml.
  GOLANGCI_LINT_VERSION: v2.12.2

jobs:
  golangci:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          echo "version set is ${{ inputs.version-set }}"
          #go-version: ${{ fromJson(inputs.version-set).go }}
          check-latest: true
          # golangci-lint-action handles all the caching for Go.
          cache: false

      # We leverage the golangci-lint action to install
      # and maintain the cache,
      # but we want to run the command ourselves.
      # The action doesn't have an install-only mode,
      # so we'll ask it to print its help output instead.
      - name: Install golangci-lint
        uses: ./.github/actions/retry
        with:
          action: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9
          with: |
            version: ${{ env.GOLANGCI_LINT_VERSION }}
            args: --help

      - name: Run golangci-lint
        run: make lint_golang
